dist: trusty
sudo: required
language: bash

env:
  global:
  - PACKER_VERSION="1.2.3"
  - TERRAFORM_VERSION="0.11.7"
  - TERRAFORM_LINT_VERSION="0.5.4"

before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh | bash
- mkdir -p "${HOME}/bin"
- touch ~/.ssh/appuser.pub
- touch ~/.ssh/appuser

install:
- sudo pip install ansible-lint
- wget "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
- unzip -o packer_${PACKER_VERSION}_linux_amd64.zip -d ${HOME}/bin
- wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
- unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d ${HOME}/bin
- wget "https://github.com/wata727/tflint/releases/download/v${TERRAFORM_LINT_VERSION}/tflint_linux_amd64.zip"
- unzip -o tflint_linux_amd64.zip -d ${HOME}/bin

script:
- cd ${TRAVIS_BUILD_DIR}/ansible
- ansible-lint playbooks/*.yml --exclude=roles/jdauphant.nginx

- cd ${TRAVIS_BUILD_DIR}
- find ./packer -name '*.json' -not -name 'variables.json' | xargs -L1 packer validate -var-file=packer/variables.json.example

- cd ${TRAVIS_BUILD_DIR}/terraform/stage
- terraform init -backend=false
- terraform validate -var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example

- cd ${TRAVIS_BUILD_DIR}/terraform/prod
- terraform init -backend=false
- terraform validate -var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example

notifications:
  slack:
    secure: Xk9AE29m9sl6HmCQgBveBfSop/5r6Vdibo/vg5eTa43KRjVX426wit1wEQrVKOVt1fN8x1yjD+BI7dCjU2nAHgJLPByikanN4LNo0jxkQi7sXRnhOaJ4LT1rSLuvw0j+JBKCseIueI8MCrGJPYqUxCwiIfkDazdIhSZiq0fTtLUCy9lZfr6ihIyNSc4HBkWygZzVTRr/wRKIp+WbFr1VPKbmQ6IG8fERm5fEVgOMuypQJTMDRJJ8uYd2B+1IivhTv6skhayn4WhHcDZUPpuxQZ3orMGm2xxniskNPR/7rVvM9Dom4NtvBmeo3LlEc+p0Y+ch7QEcI+8aFpekIrEOlKy7HvPvQ1o7Pd1DO3V+f9JcN2CkSWfD3DS+q0fprnPba7rnEgvjsCtQe2V84DiWcrvzUDGY2+LyAkP093fE/Kc8PIe0BhPCknycOxLNXCHgjvB/Nv3Gr01/4IGrAdCGhCYW/6hm34zPOdKuShSCZWKUygmT66j4fdTWNemuatJa6DJTx8zMQZFvLTYI7ulrz533k99dJcB7w/XXcv0DXyV87wPDqKinpim0MRnYrbEdLGHPnWZ1WYRvpkX6QOp4SnUM54lvF26bNm0Kk0cQvajcP4aZ4uF3J4P2vmHbr2JHCD2/DOgI0/8fhgq21bKT9N2wPnU885K67HudToFoh5s=
