---

- name: Configure mongodb
  hosts: db
  become: true
  tags: db-tag
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.jinja2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod
  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configure app
  hosts: app
  become: true
  tags: app-tag
  tasks:
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma
  - name: enable puma
    become: true
    systemd: name=puma enabled=yes
  - name: Add config for DB connection
    template:
      src: templates/db_config.jinja2
      dest: /home/appuser/db_config
      owner: appuser
      group: appuser
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

- name: Deploy application
  hosts: app
  become: true
  tags: deploy-tag
  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/appuser/reddit
      version: monolith
    notify: restart puma
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit
  handlers:
  - name: restart puma
    systemd: name=puma state=restarted
